app:
  name: app-name
  version: "0.1.0"
  commit_sha: ${_APP_COMMIT_SHA}
  build_id: ${_APP_BUILD_ID}
  build_date: ${_APP_BUILD_DATE}
  env: ${_APP_ENV}
  debug: false
server:
  host: 0.0.0.0
  port: 8080
  health_endpoint: /healthz
  info_endpoint: /info

